// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldPopulation.API.Data;

namespace WorldPopulation.API.Migrations
{
    [DbContext(typeof(WorldPopulationDbContext))]
    [Migration("20220325044408_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorldPopulation.API.Models.CountryPopulation", b =>
                {
                    b.Property<int>("CountryPopulationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coutry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Density")
                        .HasColumnType("int");

                    b.Property<int>("LandArea")
                        .HasColumnType("int");

                    b.Property<int>("NetChange")
                        .HasColumnType("int");

                    b.Property<long>("Population")
                        .HasColumnType("bigint");

                    b.Property<double>("YearlyChange")
                        .HasColumnType("float");

                    b.HasKey("CountryPopulationID");

                    b.ToTable("CountryPopulations");
                });
#pragma warning restore 612, 618
        }
    }
}
